### ISSUE TITLE
News: When Clicking icon below(first image) and then clicking the "Expand the image" icon will expand the image humongously and overlapped the whole screen.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#115]
![image](https://cloud.githubusercontent.com/assets/13363508/10875976/52116420-8173-11e5-93b7-0289911b41a3.png)
![image](https://cloud.githubusercontent.com/assets/13363508/10876057/21c708c8-8174-11e5-8d6a-68fbbd6880f6.png)

It willl turns like this one
![image](https://cloud.githubusercontent.com/assets/13363508/10876040/fcc6b9f6-8173-11e5-86ea-b43f9eb11bc4.png)
![image](https://cloud.githubusercontent.com/assets/13363508/10812313/ca54e992-7e4f-11e5-85c5-87ce5b9f1d78.png)

**Comment by maehtitan** [comment]
Unable to replicate the reported issues since all images are broken

**Comment by maehtitan** [comment]
Please apply fix in the mobile view (Ipad & Itouch & S4)

**Comment by nakul-titan** [comment]
The second expand button has been made hidden, as the image size is larger it can't fit to the mobile resolution.

**Comment by maehtitan** [comment]
@nakul-titan It doesn't fit in ipad portrait view and it will destroy the layout when you want to view the right end of the photo
![image](https://cloud.githubusercontent.com/assets/13363508/11200666/ce231f68-8d12-11e5-9a74-5471b6e94949.png)
![image](https://cloud.githubusercontent.com/assets/13363508/11200668/d678ed6e-8d12-11e5-82c4-0fcbc448be5c.png)
