### ISSUE TITLE
News Single View: Featured image are stretched

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#126]

**Comment by nakul-titan** [comment]
As per design news single page contains full width image please try uploading bigger size image.

**Comment by maehtitan** [comment]
@nakul-titan As per design no image sample that fits the whole width of the page only the line of text
![image](https://cloud.githubusercontent.com/assets/13363508/11200691/000ff8c0-8d13-11e5-90e4-2828e5099242.png)

**Comment by nakul-titan** [comment]
As there is no image shown in the design have removed it the image from news single page.

**Comment by maehtitan** [comment]
No, it doesn't mean you need to remove the image. Image is shown in News list page, so basically it will reflect in the new single view. Just retain the image resolution not removing it. Please 

Thanks
