### ISSUE TITLE
Homepage - Content: Please make the list item styled like the photo below just like the company profile page, list icons are vertically aligned and <ul> are horizontally align

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#133]
![image](https://cloud.githubusercontent.com/assets/13363508/11201098/fa7823f8-8d15-11e5-8efb-87fa892b4dfc.png)

**Comment by nakul-titan** [comment]
The items you are referring to are not list items, that is a paragraph text with br tags.

**Comment by maehtitan** [comment]
<b>The one I was referring was a list items previously but it looks like this https://github.com/titan-cebu/Alto-Capital/issues/133#issuecomment-157693920 when list items are used

I witnessed the changes coz I was doing the QA while somebody added the final contents.

<b>That's why the one who added the content removed the list items just to make the line of text displays fine and center aligned

**Comment by nakul-titan** [comment]
I have fixed it just need to push the styles to stage

**Comment by maehtitan** [comment]
Thanks :)
