### ISSUE TITLE
Pre-Footer: Client logo images aren't resized properly

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Alto-Capital#20]
![home - 02](https://cloud.githubusercontent.com/assets/11186359/10157615/06743558-66be-11e5-9f97-6caf3cd410d8.jpg)

**Comment by nakul-titan** [comment]
This is not applicable in DMS. Client has to upload properly cropped logo.

**Comment by bernardtitan** [comment]
I'm not sure this is correct as the image was already resized automatically, it just wasn't resized small enough.

**Comment by maehtitan** [comment]
still not fixed
