### ISSUE TITLE
Header: The "Client Login" button doesn't do anything

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Alto-Capital#23]

**Comment by nakul-titan** [comment]
No design is provided for Client Login. So currently it is liked to #.

**Comment by bernardtitan** [comment]
Kindly ask Salman, so he can ask for designs. This kind of thing requires development, even if no designs are provided.

**Comment by maehtitan** [comment]
It is not supposed to redirect on the back-end link, I believe it is a login pop up form

**Comment by nakul-titan** [comment]
There is no functionality for front-end login, that's why it is opening back-end login in new tab.

**Comment by maehtitan** [comment]
![image](https://cloud.githubusercontent.com/assets/13363508/10987026/49cee720-846a-11e5-935e-9c1eb3c93bfc.png)

**Comment by maehtitan** [comment]
Not yet fixed. Where to add the link? The client should have the ability to add the link since it is redirected to a 3rd party link. 

Thanks

**Comment by nakul-titan** [comment]
Client can add link in titan theme options, 
![titan theme options alto capital wordpress 2015-11-09 09-58-10](https://cloud.githubusercontent.com/assets/13461911/11025947/7ee60c8a-86c8-11e5-8b33-1fa771f7fb08.png)
