### ISSUE TITLE
Admin - Revolution Slider: Overlapped text at the bottom

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#42]
![image](https://cloud.githubusercontent.com/assets/13363508/10238154/028412f6-68ee-11e5-89be-cc4ef8b30b2f.png)

**Comment by maehtitan** [comment]
Still not yet fixed

**Comment by nakul-titan** [comment]
Those styles are coming from the default revolution slider, which cannot be changed.
