### ISSUE TITLE
Company Profile: Compressed from the above item post after adding a new profile name, profile image, and profile description. I was wondering when do the class "vc_custom_('random-numbers-here')" occurs? Is it generated automatically? Because there was a margin-top set to 50px which is also set to important which I think it was manually added. 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#46]
<b>QA Tester post item is perfectly align for I only use the "clone this row" 

![image](https://cloud.githubusercontent.com/assets/13363508/10239922/b1429042-6907-11e5-867d-9798062d84e7.png)

![image](https://cloud.githubusercontent.com/assets/13363508/10240708/3685b4c8-6912-11e5-9a3f-8c5a7ff5fb82.png)

**Comment by nakul-titan** [comment]
Yes it will generate automatically from visual composer.

**Comment by maehtitan** [comment]
So how did you add another profile which has proper spacing and alignment by default?

**Comment by nakul-titan** [comment]
Well when you add a new row we can set the rows padding, margin, border etc. in the row settings
![row settings](https://cloud.githubusercontent.com/assets/13461911/10844571/82798fec-7f26-11e5-8408-e9cbc19c5e6a.png)

Or you can just make a copy of the above row and change the content
