### ISSUE TITLE
General: Incorrect default no-image, use a light + grayscale version of the client’s logo as per standard link below. 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#50]
https://knowledgebase.titanweb.com.au/implementation-practices/woocommerce/default-no-image

![image](https://cloud.githubusercontent.com/assets/13363508/10241206/6f0b442e-6918-11e5-99d8-97d2f6de519c.png)

**Comment by nakul-titan** [comment]
Default Image is coming from parent theme and we don't have permission to edit parent theme files.
