### ISSUE TITLE
Pre-Footer: The widgets showing market data aren't displayed

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Alto-Capital#6]

**Comment by nakul-titan** [comment]
Hi Bernard,
Carin has created an AC ticket for Extra development for the feeds to be done later.
Please refer:
https://projects.titanweb.com.au/public/index.php?path_info=projects/alto-capital-pack1responsivephotosform/tasks/25

**Comment by bernardtitan** [comment]
Fair enough, label changed to won'tfix as it wasn't documented that there was a separate ticket created for it.
