### ISSUE TITLE
W3C - Sitemap: 6 Errors and 1 warning

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#87]
https://validator.w3.org/nu/?doc=http%3A%2F%2Falto-capital.stage.titanweb.com.au%2Fsitemap%2F
![image](https://cloud.githubusercontent.com/assets/13363508/10275090/373d58c8-6b77-11e5-873b-b3fba9913161.png)

**Comment by nakul-titan** [comment]
Cant resolved Visual Composer errors.
