### ISSUE TITLE
W3C - Thank you: 5 Errors 2 Warnings

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#88]
https://validator.w3.org/nu/?doc=http%3A%2F%2Falto-capital.stage.titanweb.com.au%2Fthank-you%2F
![image](https://cloud.githubusercontent.com/assets/13363508/10275126/91d61aa4-6b77-11e5-91c8-d63472bd8986.png)

**Comment by nakul-titan** [comment]
HTML errors has been resolved, can't resolved Visual Composer error.
