### ISSUE TITLE
W3C - Company Profile: 7 Errors and 2 Warnings

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#89]
https://validator.w3.org/nu/?doc=http%3A%2F%2Falto-capital.stage.titanweb.com.au%2Fcompany-profile%2F
![image](https://cloud.githubusercontent.com/assets/13363508/10275191/1be0b182-6b78-11e5-98c1-5534b9cba947.png)

**Comment by nakul-titan** [comment]
Errors are due to Visual Composer we cant fix it.
