### ISSUE TITLE
W3C - Contact: 13 Errors and 2 Warnings

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#90]
https://validator.w3.org/nu/?doc=http%3A%2F%2Falto-capital.stage.titanweb.com.au%2Fcontact%2F
![image](https://cloud.githubusercontent.com/assets/13363508/10275251/905a441a-6b78-11e5-876a-c7fac16ed6cd.png)

**Comment by nakul-titan** [comment]
http://alto-capital.stage.titanweb.com.au/contact/
