### ISSUE TITLE
W3C - Services: 15 Errors and 2 Warnings

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#91]
https://validator.w3.org/nu/?doc=http%3A%2F%2Falto-capital.stage.titanweb.com.au%2Fservices%2F
![image](https://cloud.githubusercontent.com/assets/13363508/10275336/3aab84f6-6b79-11e5-9daa-9452e257793f.png)

**Comment by nakul-titan** [comment]
Errors are due to Visual Composer we cant fix it.
