### ISSUE TITLE
W3C - Privacy Policy: 5 Errors and 2 Warnings

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#93]
https://validator.w3.org/nu/?doc=http%3A%2F%2Falto-capital.stage.titanweb.com.au%2Fprivacy-policy%2F

![image](https://cloud.githubusercontent.com/assets/13363508/10275459/3dfa3ea8-6b7a-11e5-82bb-8fcb9aea78c1.png)

**Comment by nakul-titan** [comment]
Errors are due to Visual Composer we cant fix it.
