### ISSUE TITLE
W3C - Presentation: 4 Errors

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#94]
https://validator.w3.org/nu/?doc=http%3A%2F%2Falto-capital.stage.titanweb.com.au%2Fpresentations%2F
![image](https://cloud.githubusercontent.com/assets/13363508/10275477/5f3de218-6b7a-11e5-9221-c8f800bdba35.png)

**Comment by nakul-titan** [comment]
Errors are due to Visual Composer we cant fix it.
