### ISSUE TITLE
W3C - News: 8 Errors and 2 Warnings

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#95]
https://validator.w3.org/nu/?doc=http%3A%2F%2Falto-capital.stage.titanweb.com.au%2Fnews%2F

![image](https://cloud.githubusercontent.com/assets/13363508/10275520/a2c43776-6b7a-11e5-9220-d1a94ddc0135.png)

**Comment by nakul-titan** [comment]
Errors are due to Visual Composer we cant fix it.
