### ISSUE TITLE
W3C - News Single View: 12 Errors and 3 Warnings

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#96]
https://validator.w3.org/nu/?doc=http%3A%2F%2Falto-capital.stage.titanweb.com.au%2Fnews-5%2F
![image](https://cloud.githubusercontent.com/assets/13363508/10275572/fca9d39a-6b7a-11e5-8cef-b52f6e63fc2a.png)

**Comment by nakul-titan** [comment]
HTML bugs has been fixed and some of them are from Visual Composer and we cant fix it.
