### ISSUE TITLE
W3C - Homepage: 16 Errors and 2 Warnings

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#97]
https://validator.w3.org/nu/?doc=http%3A%2F%2Falto-capital.stage.titanweb.com.au%2F
![image](https://cloud.githubusercontent.com/assets/13363508/10275625/717a4dc6-6b7b-11e5-8779-1a8bd5b3d737.png)

**Comment by nakul-titan** [comment]
Errors are due to Visual Composer we can't resolve it.
