### ISSUE TITLE
W3C - FSG: 5 Errors and 2 Warnings

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#98]
https://validator.w3.org/nu/?doc=http%3A%2F%2Falto-capital.stage.titanweb.com.au%2Ffsg%2F
![image](https://cloud.githubusercontent.com/assets/13363508/10275758/97e851aa-6b7c-11e5-8f7b-789f45285604.png)

**Comment by nakul-titan** [comment]
4 errors has been resolved and 1 error is from Visual Composer we cant resolved it.
