### ISSUE TITLE
W3C - FAQ: 12 Errors and 2 Warnings

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Alto-Capital#99]
https://validator.w3.org/nu/?doc=http%3A%2F%2Falto-capital.stage.titanweb.com.au%2Ffaq%2F
![image](https://cloud.githubusercontent.com/assets/13363508/10275785/e28f1c84-6b7c-11e5-83aa-a113e395cf41.png)

**Comment by nakul-titan** [comment]
HTML errors has been resolved and some of the errors are coming from Visual Composer and we can't resolve it.

**Comment by maehtitan** [comment]
Only 4 issues has been fixed and the rest are wontfix.
